INSERT INTO games (tournament_id,category,week_number,game_date,game_place,team_1,team_2) SELECT 2 AS tournament_id,'MIXTO' AS category,9 AS week_number,STR_TO_DATE(CONCAT(TRIM('11/4/2024'),' ',TRIM(REPLACE('5:30 P.M.','.',''))), '%m/%d/%Y %h:%i %p') AS game_date,TRIM('ARRIBA') AS game_place,fn_get_team_id('MIXTO','RENCOROSOS') AS team_1,fn_get_team_id('MIXTO','L@S PEQUES') AS team_2 FROM DUAL;
INSERT INTO games (tournament_id,category,week_number,game_date,game_place,team_1,team_2) SELECT 2 AS tournament_id,'FEMENIL' AS category,9 AS week_number,STR_TO_DATE(CONCAT(TRIM('11/4/2024'),' ',TRIM(REPLACE('6:30 P.M.','.',''))), '%m/%d/%Y %h:%i %p') AS game_date,TRIM('ARRIBA') AS game_place,fn_get_team_id('FEMENIL','LAS PEQUES') AS team_1,fn_get_team_id('FEMENIL','PREPA') AS team_2 FROM DUAL;
INSERT INTO games (tournament_id,category,week_number,game_date,game_place,team_1,team_2) SELECT 2 AS tournament_id,'MIXTO' AS category,9 AS week_number,STR_TO_DATE(CONCAT(TRIM('11/4/2024'),' ',TRIM(REPLACE('7:30 P.M.','.',''))), '%m/%d/%Y %h:%i %p') AS game_date,TRIM('ARRIBA') AS game_place,fn_get_team_id('MIXTO','LOS DEL BASQUET') AS team_1,fn_get_team_id('MIXTO','ROJAS MIX') AS team_2 FROM DUAL;
INSERT INTO games (tournament_id,category,week_number,game_date,game_place,team_1,team_2) SELECT 2 AS tournament_id,'MIXTO' AS category,9 AS week_number,STR_TO_DATE(CONCAT(TRIM('11/4/2024'),' ',TRIM(REPLACE('8:30 P.M.','.',''))), '%m/%d/%Y %h:%i %p') AS game_date,TRIM('ARRIBA') AS game_place,fn_get_team_id('MIXTO','VIKINGOS') AS team_1,fn_get_team_id('MIXTO','LA SELECCIÓN') AS team_2 FROM DUAL;

INSERT INTO games (tournament_id,category,week_number,game_date,game_place,team_1,team_2) SELECT 2 AS tournament_id,'MIXTO' AS category,9 AS week_number,STR_TO_DATE(CONCAT(TRIM('11/4/2024'),' ',TRIM(REPLACE('5:30 P.M.','.',''))), '%m/%d/%Y %h:%i %p') AS game_date,TRIM('ABAJO') AS game_place,fn_get_team_id('MIXTO','LOS DEL BASQUET') AS team_1,fn_get_team_id('MIXTO','FENIX') AS team_2 FROM DUAL;
INSERT INTO games (tournament_id,category,week_number,game_date,game_place,team_1,team_2) SELECT 2 AS tournament_id,'FEMENIL' AS category,9 AS week_number,STR_TO_DATE(CONCAT(TRIM('11/4/2024'),' ',TRIM(REPLACE('6:30 P.M.','.',''))), '%m/%d/%Y %h:%i %p') AS game_date,TRIM('ABAJO') AS game_place,fn_get_team_id('FEMENIL','TIX') AS team_1,fn_get_team_id('FEMENIL','NOVAS') AS team_2 FROM DUAL;
INSERT INTO games (tournament_id,category,week_number,game_date,game_place,team_1,team_2) SELECT 2 AS tournament_id,'MIXTO' AS category,9 AS week_number,STR_TO_DATE(CONCAT(TRIM('11/4/2024'),' ',TRIM(REPLACE('7:30 P.M.','.',''))), '%m/%d/%Y %h:%i %p') AS game_date,TRIM('ABAJO') AS game_place,fn_get_team_id('MIXTO','VIKINGOS') AS team_1,fn_get_team_id('MIXTO','L@S PEQUES') AS team_2 FROM DUAL;



INSERT INTO games (tournament_id,category,week_number,game_date,game_place,team_1,team_2) SELECT 2 AS tournament_id,'MIXTO' AS category,9 AS week_number,STR_TO_DATE(CONCAT(TRIM('11/5/2024'),' ',TRIM(REPLACE('5:30 P.M.','.',''))), '%m/%d/%Y %h:%i %p') AS game_date,TRIM('ARRIBA') AS game_place,fn_get_team_id('MIXTO','FENIX') AS team_1,fn_get_team_id('MIXTO','PECHOCHOS') AS team_2 FROM DUAL;
INSERT INTO games (tournament_id,category,week_number,game_date,game_place,team_1,team_2) SELECT 2 AS tournament_id,'VARONIL' AS category,9 AS week_number,STR_TO_DATE(CONCAT(TRIM('11/5/2024'),' ',TRIM(REPLACE('6:30 P.M.','.',''))), '%m/%d/%Y %h:%i %p') AS game_date,TRIM('ARRIBA') AS game_place,fn_get_team_id('VARONIL','CIERVOS') AS team_1,fn_get_team_id('VARONIL','DESPEINADOS') AS team_2 FROM DUAL;
INSERT INTO games (tournament_id,category,week_number,game_date,game_place,team_1,team_2) SELECT 2 AS tournament_id,'MIXTO' AS category,9 AS week_number,STR_TO_DATE(CONCAT(TRIM('11/5/2024'),' ',TRIM(REPLACE('7:30 P.M.','.',''))), '%m/%d/%Y %h:%i %p') AS game_date,TRIM('ARRIBA') AS game_place,fn_get_team_id('MIXTO','VENGADORES') AS team_1,fn_get_team_id('MIXTO','LOS OLVIDADOS') AS team_2 FROM DUAL;


INSERT INTO games (tournament_id,category,week_number,game_date,game_place,team_1,team_2) SELECT 2 AS tournament_id,'MIXTO' AS category,9 AS week_number,STR_TO_DATE(CONCAT(TRIM('11/5/2024'),' ',TRIM(REPLACE('5:30 P.M.','.',''))), '%m/%d/%Y %h:%i %p') AS game_date,TRIM('ABAJO') AS game_place,fn_get_team_id('MIXTO','VENGADORES') AS team_1,fn_get_team_id('MIXTO','PECHOCHOS') AS team_2 FROM DUAL;
INSERT INTO games (tournament_id,category,week_number,game_date,game_place,team_1,team_2) SELECT 2 AS tournament_id,'MIXTO' AS category,9 AS week_number,STR_TO_DATE(CONCAT(TRIM('11/5/2024'),' ',TRIM(REPLACE('6:30 P.M.','.',''))), '%m/%d/%Y %h:%i %p') AS game_date,TRIM('ABAJO') AS game_place,fn_get_team_id('MIXTO','LA SELECCIÓN') AS team_1,fn_get_team_id('MIXTO','MIXED SQUIRRELS') AS team_2 FROM DUAL;
INSERT INTO games (tournament_id,category,week_number,game_date,game_place,team_1,team_2) SELECT 2 AS tournament_id,'VARONIL' AS category,9 AS week_number,STR_TO_DATE(CONCAT(TRIM('11/5/2024'),' ',TRIM(REPLACE('7:30 P.M.','.',''))), '%m/%d/%Y %h:%i %p') AS game_date,TRIM('ABAJO') AS game_place,fn_get_team_id('VARONIL','TOROS') AS team_1,fn_get_team_id('VARONIL','LOS UNICOS') AS team_2 FROM DUAL;



INSERT INTO games (tournament_id,category,week_number,game_date,game_place,team_1,team_2) SELECT 2 AS tournament_id,'MIXTO' AS category,9 AS week_number,STR_TO_DATE(CONCAT(TRIM('11/6/2024'),' ',TRIM(REPLACE('5:30 P.M.','.',''))), '%m/%d/%Y %h:%i %p') AS game_date,TRIM('ARRIBA') AS game_place,fn_get_team_id('MIXTO','MIXTICOS') AS team_1,fn_get_team_id('MIXTO','MIXED SQUIRRELS') AS team_2 FROM DUAL;
INSERT INTO games (tournament_id,category,week_number,game_date,game_place,team_1,team_2) SELECT 2 AS tournament_id,'MIXTO' AS category,9 AS week_number,STR_TO_DATE(CONCAT(TRIM('11/6/2024'),' ',TRIM(REPLACE('6:30 P.M.','.',''))), '%m/%d/%Y %h:%i %p') AS game_date,TRIM('ARRIBA') AS game_place,fn_get_team_id('MIXTO','MIXTICOS') AS team_1,fn_get_team_id('MIXTO','ROJAS MIX') AS team_2 FROM DUAL;
INSERT INTO games (tournament_id,category,week_number,game_date,game_place,team_1,team_2) SELECT 2 AS tournament_id,'MIXTO' AS category,9 AS week_number,STR_TO_DATE(CONCAT(TRIM('11/6/2024'),' ',TRIM(REPLACE('7:30 P.M.','.',''))), '%m/%d/%Y %h:%i %p') AS game_date,TRIM('ARRIBA') AS game_place,fn_get_team_id('MIXTO','MIXTICOS') AS team_1,fn_get_team_id('MIXTO','L@S PEQUES') AS team_2 FROM DUAL;


INSERT INTO games (tournament_id,category,week_number,game_date,game_place,team_1,team_2) SELECT 2 AS tournament_id,'VARONIL' AS category,9 AS week_number,STR_TO_DATE(CONCAT(TRIM('11/6/2024'),' ',TRIM(REPLACE('5:30 P.M.','.',''))), '%m/%d/%Y %h:%i %p') AS game_date,TRIM('ABAJO') AS game_place,fn_get_team_id('VARONIL','CUERVOS') AS team_1,fn_get_team_id('VARONIL','ARDILLAS') AS team_2 FROM DUAL;
INSERT INTO games (tournament_id,category,week_number,game_date,game_place,team_1,team_2) SELECT 2 AS tournament_id,'MIXTO' AS category,9 AS week_number,STR_TO_DATE(CONCAT(TRIM('11/6/2024'),' ',TRIM(REPLACE('6:30 P.M.','.',''))), '%m/%d/%Y %h:%i %p') AS game_date,TRIM('ABAJO') AS game_place,fn_get_team_id('MIXTO','LA SELECCIÓN') AS team_1,fn_get_team_id('MIXTO','L@S PEQUES') AS team_2 FROM DUAL;
INSERT INTO games (tournament_id,category,week_number,game_date,game_place,team_1,team_2) SELECT 2 AS tournament_id,'MIXTO' AS category,9 AS week_number,STR_TO_DATE(CONCAT(TRIM('11/6/2024'),' ',TRIM(REPLACE('7:30 P.M.','.',''))), '%m/%d/%Y %h:%i %p') AS game_date,TRIM('ABAJO') AS game_place,fn_get_team_id('MIXTO','WINNERS') AS team_1,fn_get_team_id('MIXTO','PECHOCHOS') AS team_2 FROM DUAL;



INSERT INTO games (tournament_id,category,week_number,game_date,game_place,team_1,team_2) SELECT 2 AS tournament_id,'FEMENIL' AS category,9 AS week_number,STR_TO_DATE(CONCAT(TRIM('11/7/2024'),' ',TRIM(REPLACE('5:30 P.M.','.',''))), '%m/%d/%Y %h:%i %p') AS game_date,TRIM('ABAJO') AS game_place,fn_get_team_id('FEMENIL','TIX') AS team_1,fn_get_team_id('FEMENIL','PREPA') AS team_2 FROM DUAL;
INSERT INTO games (tournament_id,category,week_number,game_date,game_place,team_1,team_2) SELECT 2 AS tournament_id,'MIXTO' AS category,9 AS week_number,STR_TO_DATE(CONCAT(TRIM('11/7/2024'),' ',TRIM(REPLACE('6:30 P.M.','.',''))), '%m/%d/%Y %h:%i %p') AS game_date,TRIM('ABAJO') AS game_place,fn_get_team_id('MIXTO','RENCOROSOS') AS team_1,fn_get_team_id('MIXTO','GALACTICOS') AS team_2 FROM DUAL;
INSERT INTO games (tournament_id,category,week_number,game_date,game_place,team_1,team_2) SELECT 2 AS tournament_id,'MIXTO' AS category,9 AS week_number,STR_TO_DATE(CONCAT(TRIM('11/7/2024'),' ',TRIM(REPLACE('7:30 P.M.','.',''))), '%m/%d/%Y %h:%i %p') AS game_date,TRIM('ABAJO') AS game_place,fn_get_team_id('MIXTO','WINNERS') AS team_1,fn_get_team_id('MIXTO','MIXED SQUIRRELS') AS team_2 FROM DUAL;