spring:
  jpa:
    show-sql: false
    hibernate:
      #update don't create and drop
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/tvmtz_stg
    username: root
    password: M4r1@Db_R0ot_P4$sw0rd
  application:
    name: volley.api
  messages:
    basename: i18n/messages
    always-use-message-format: false
    cache-duration:
    encoding: UTF-8
    fallback-to-system-locale: true
    use-code-as-default-message: false
  test:
    database:
      replace: none
server:
  port: 8082
  error:
    include-stacktrace: never
    # include-message: never
app:
  content-type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub