spring:
  jpa:
    show-sql: true
    hibernate:
      # update don't create and drop
      ddl-auto: update
    properties:
      hibernate:

        format_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/cfs_dev
    username: root
    password: p4$sw0rd
token:
  signing:
    key: s3cr3tK3yF0rChurchF1n4nc14lSyst3mAppl1c4t10nG3n3rat3dM4nu4lK3tF0rT3st1ng
server:
  port: 8081