spring:
    jpa:
        show-sql: true
        hibernate:
            #update don't create and drop
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/volley_dev
        username: root
        password: p4$sw0rd
    application:
        name:volley.api
server:
    port: 8082