logging:
  level:
    root: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
spring:
  application:
    name: spring-security-demo
  jpa:
    show-sql: true
    hibernate:
      # update don't create and drop
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/security_demo
    username: root
    password: M4r1@Db_R0ot_P4$sw0rd
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub